
"""Add bid_documents table

Revision ID: 8bbaed0b6bad
Revises: db74ead805f0
Create Date: 2026-02-07 16:20:31.442059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bbaed0b6bad'
down_revision: Union[str, None] = 'db74ead805f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bid_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('analysis_result', sa.JSON(), nullable=True),
    sa.Column('analysis_status', sa.String(length=50), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('bidder_name', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('bid_documents_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('bid_documents_pkey'))
    )
    op.create_index(op.f('bid_documents_id_idx'), 'bid_documents', ['id'], unique=False)
    op.create_index(op.f('bid_documents_user_id_idx'), 'bid_documents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('bid_documents_user_id_idx'), table_name='bid_documents')
    op.drop_index(op.f('bid_documents_id_idx'), table_name='bid_documents')
    op.drop_table('bid_documents')
    # ### end Alembic commands ###
